# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: delete old
        run: rm -Rf javaPatchNotes.json

      # Runs a set of commands using the runners shell
      - name: get new
        run: wget https://launchercontent.mojang.com/javaPatchNotes.json
      
      - uses: stefanzweifel/git-auto-commit-action@v4
      
